"""empty message

Revision ID: 72d8488f994d
Revises: 2d8fba7cd33c
Create Date: 2022-06-20 00:24:18.258788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72d8488f994d'
down_revision = '2d8fba7cd33c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('name', sa.String(length=80), nullable=False))
    op.drop_column('contact', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('password', mysql.VARCHAR(length=80), nullable=False))
    op.drop_column('contact', 'name')
    # ### end Alembic commands ###
